### ISSUE TITLE
wiki review

### ISSUE THREAD

**Issue by javiermortiz** [CalebAmes/ProgramHunt#1]
Hi team!
good job with the schema - you added constraints and associations. I like that you kept it simple and intuitive. There is some styling to be fixed in your feature list wiki. I also believe you are missing listing Programs (Products) as one of your features which I believe is the main feature.
You might want to add an image or video to each Program (Product) and even for Users. If that is the case you'd need a column to store that data on each table.

**Comment by CalebAmes** [comment]
It's all updated. Thanks Javier
